on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo & submodules
        uses: actions/checkout@v4
        with:
            submodules: recursive
      - name: Build toolchain
        run: scripts/build.sh
      - run: scripts/release.sh
