on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: nstalll packages
        run: |
          sudo apt-get update
          sudo apt-get -y install expect
      - name: Build test harness
        run: scripts/build.sh --infra
      - name: Build toolchain
        run: scripts/build.sh
      - name: Run tests
        run: scripts/build.sh --test-tt
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-tests
          path: build/g++.sum
      - name: Release toolchain
        run: scripts/release.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-build
          path: build/sfpi-*
          compression-level: 0
